//! Knowledge-base collection existence doctor.
//!
//! On 2026-05-04 several cartridge `seed.py` files referenced `kb_collection=` values
//! that did not match either (a) the platform-default template `tenant_{tenant_id}_knowledge`
//! generated by `example-api/example/routers/ingest.py:835`, nor (b) any collection that
//! actually existed in Milvus. The downstream effect is silent: the agent's knowledge
//! tool calls `/v2/search/<col>/hybrid`, gets a 404, the tool returns empty, and the LLM
//! degrades to "I don't have that information" without any visible failure surface.
//!
//! This doctor is purely STATIC. It does not call Milvus. It cross-references each
//! `kb_collection="..."` literal in cartridge seeds and `example-api/scripts/seed_*.py`
//! against:
//!
//!   1. an optional workspace manifest at `deploy/expected_milvus_collections.txt`
//!      (one collection per line, comments with `#` allowed), and
//!   2. the platform-default template `tenant_{tenant_id}_knowledge` for every tenant
//!      declared in `cartridges/*/cartridge.toml`'s `tenant = "..."` field.
//!
//! A `kb_collection` value that matches neither produces a warning. Live Milvus
//! reachability is a different doctor (`milvus-reachability`).

use std::collections::BTreeSet;
use std::path::Path;
use std::time::Instant;

use ignore::WalkBuilder;
use regex::Regex;
use serde_json::json;

use super::Doctor;
use super::utils::{query_id, read_text};
use crate::model::{EvidenceItem, QueryEnvelope, RepoIndex};

pub struct KbCollectionExistsDoctor;

impl Doctor for KbCollectionExistsDoctor {
    fn name(&self) -> &'static str {
        "kb-collection-exists"
    }

    fn description(&self) -> &'static str {
        "Cross-references `kb_collection=\"...\"` literals in cartridge `seed.py` and `example-api/scripts/seed_*.py` against `deploy/expected_milvus_collections.txt` and the platform-default `tenant_{tenant_id}_knowledge` template. Catches drift where seeds name a collection that does not exist in Milvus, causing silent /v2/search/<col>/hybrid 404s."
    }

    fn run(&self, _index: &RepoIndex, root: &Path) -> QueryEnvelope {
        doctor_kb_collection_exists(root)
    }
}

const MANIFEST_REL: &str = "deploy/expected_milvus_collections.txt";

#[derive(Debug)]
struct SeedHit {
    rel_path: String,
    line: usize,
    agent_slug: Option<String>,
    kb_collection: String,
}

pub fn doctor_kb_collection_exists(root: &Path) -> QueryEnvelope {
    let started = Instant::now();
    let mut warnings = Vec::new();
    let mut entities = Vec::new();
    let mut evidence = Vec::new();

    // 1. Collect tenants declared by cartridge.toml files.
    let tenants = collect_cartridge_tenants(root, &mut warnings);

    // 2. Load manifest (if present).
    let (manifest, manifest_loaded) = load_manifest(root, &mut warnings);

    // 3. Collect seed hits.
    let mut hits: Vec<SeedHit> = Vec::new();
    collect_cartridge_seed_hits(root, &mut hits, &mut warnings);
    collect_api_script_seed_hits(root, &mut hits, &mut warnings);

    // 4. Cross-reference.
    let expected_template: BTreeSet<String> = tenants
        .iter()
        .filter(|t| !t.is_empty())
        .map(|t| format!("tenant_{}_knowledge", t))
        .collect();

    let mut unresolved: Vec<&SeedHit> = Vec::new();
    for hit in &hits {
        if manifest.contains(&hit.kb_collection) {
            continue;
        }
        if expected_template.contains(&hit.kb_collection) {
            continue;
        }
        unresolved.push(hit);
    }

    for hit in &unresolved {
        let agent_part = hit
            .agent_slug
            .as_ref()
            .map(|s| format!(" (agent `{}`)", s))
            .unwrap_or_default();
        warnings.push(format!(
            "{}:{}: kb_collection `{}`{} is referenced but does not match the platform-default template `tenant_{{tenant_id}}_knowledge` and is not listed in {} -- either add it to the manifest or align the seed to the platform default",
            hit.rel_path,
            hit.line,
            hit.kb_collection,
            agent_part,
            MANIFEST_REL,
        ));
        evidence.push(EvidenceItem {
            kind: "kb_collection_unresolved".to_string(),
            path: hit.rel_path.clone(),
            line: Some(hit.line),
            detail: format!(
                "kb_collection=\"{}\"{} matches neither manifest nor tenant template",
                hit.kb_collection, agent_part
            ),
        });
    }

    entities.push(json!({
        "doctor": "kb-collection-exists",
        "manifest_path": MANIFEST_REL,
        "manifest_loaded": manifest_loaded,
        "manifest_entries": manifest.iter().collect::<Vec<_>>(),
        "tenants": tenants.iter().collect::<Vec<_>>(),
        "tenant_template_expected": expected_template.iter().collect::<Vec<_>>(),
        "seed_hits": hits.iter().map(|h| json!({
            "path": h.rel_path,
            "line": h.line,
            "agent_slug": h.agent_slug,
            "kb_collection": h.kb_collection,
        })).collect::<Vec<_>>(),
        "unresolved_count": unresolved.len(),
    }));

    let summary = if unresolved.is_empty() {
        format!(
            "all {} kb_collection seed reference(s) resolved against manifest ({} entries) or tenant template ({} tenants)",
            hits.len(),
            manifest.len(),
            tenants.len(),
        )
    } else {
        format!(
            "{} kb_collection seed reference(s) do not match manifest or tenant_{{tenant_id}}_knowledge template -- silent /v2/search 404 risk",
            unresolved.len(),
        )
    };

    QueryEnvelope {
        schema_version: crate::model::SCHEMA_VERSION.to_string(),
        query_id: query_id("doctor_kb_collection_exists"),
        kind: "doctor".to_string(),
        summary,
        confidence: if unresolved.is_empty() { 0.95 } else { 0.6 },
        entities,
        evidence,
        warnings,
        meta: None,
        timing_ms: started.elapsed().as_millis(),
    }
}

fn load_manifest(root: &Path, warnings: &mut Vec<String>) -> (BTreeSet<String>, bool) {
    let path = root.join(MANIFEST_REL);
    if !path.is_file() {
        warnings.push(format!(
            "{} is missing -- doctor falls back to the `tenant_{{tenant_id}}_knowledge` template only; create the manifest to recognize bespoke collections",
            MANIFEST_REL
        ));
        return (BTreeSet::new(), false);
    }
    let mut io = Vec::new();
    let body = match read_text(&path, &mut io) {
        Some(b) => b,
        None => {
            warnings.extend(io);
            return (BTreeSet::new(), false);
        }
    };
    let mut set = BTreeSet::new();
    for raw in body.lines() {
        let line = raw.split('#').next().unwrap_or("").trim();
        if line.is_empty() {
            continue;
        }
        set.insert(line.to_string());
    }
    (set, true)
}

fn collect_cartridge_tenants(root: &Path, warnings: &mut Vec<String>) -> BTreeSet<String> {
    let mut tenants = BTreeSet::new();
    let cartridges_root = root.join("cartridges");
    if !cartridges_root.is_dir() {
        return tenants;
    }
    let mut builder = WalkBuilder::new(&cartridges_root);
    builder.hidden(false);
    builder.git_ignore(true);
    builder.require_git(false);
    builder.max_depth(Some(2));

    for dent in builder.build().flatten() {
        let path = dent.path();
        if !path.is_file() {
            continue;
        }
        let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
            continue;
        };
        if name != "cartridge.toml" {
            continue;
        }
        let mut io = Vec::new();
        let body = match read_text(path, &mut io) {
            Some(b) => b,
            None => {
                warnings.extend(io);
                continue;
            }
        };
        let parsed: toml::Value = match toml::from_str(&body) {
            Ok(v) => v,
            Err(err) => {
                warnings.push(format!(
                    "failed to parse {}: {err}",
                    path.strip_prefix(root)
                        .map(|p| p.display().to_string())
                        .unwrap_or_else(|_| path.display().to_string()),
                ));
                continue;
            }
        };
        if let Some(tenant) = lookup_tenant(&parsed)
            && !tenant.is_empty()
        {
            tenants.insert(tenant.to_string());
        }
    }
    tenants
}

fn lookup_tenant(value: &toml::Value) -> Option<&str> {
    // Common shapes: top-level `tenant = "..."` or under `[cartridge]`.
    if let Some(s) = value.get("tenant").and_then(|v| v.as_str()) {
        return Some(s);
    }
    if let Some(s) = value
        .get("cartridge")
        .and_then(|c| c.get("tenant"))
        .and_then(|v| v.as_str())
    {
        return Some(s);
    }
    None
}

fn collect_cartridge_seed_hits(root: &Path, hits: &mut Vec<SeedHit>, warnings: &mut Vec<String>) {
    let cartridges_root = root.join("cartridges");
    if !cartridges_root.is_dir() {
        return;
    }
    let mut builder = WalkBuilder::new(&cartridges_root);
    builder.hidden(false);
    builder.git_ignore(true);
    builder.require_git(false);
    builder.max_depth(Some(3));

    for dent in builder.build().flatten() {
        let path = dent.path();
        if !path.is_file() {
            continue;
        }
        let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
            continue;
        };
        if name != "seed.py" {
            continue;
        }
        scan_seed_file(root, path, hits, warnings);
    }
}

fn collect_api_script_seed_hits(root: &Path, hits: &mut Vec<SeedHit>, warnings: &mut Vec<String>) {
    let scripts_root = root.join("example-api/scripts");
    if !scripts_root.is_dir() {
        return;
    }
    let entries = match std::fs::read_dir(&scripts_root) {
        Ok(e) => e,
        Err(err) => {
            warnings.push(format!("failed to read example-api/scripts/: {err}"));
            return;
        }
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
            continue;
        };
        if !(name.starts_with("seed_") && name.ends_with(".py")) {
            continue;
        }
        scan_seed_file(root, &path, hits, warnings);
    }
}

fn scan_seed_file(root: &Path, path: &Path, hits: &mut Vec<SeedHit>, warnings: &mut Vec<String>) {
    let mut io = Vec::new();
    let body = match read_text(path, &mut io) {
        Some(b) => b,
        None => {
            warnings.extend(io);
            return;
        }
    };
    let rel = path
        .strip_prefix(root)
        .map(|p| p.to_string_lossy().replace('\\', "/"))
        .unwrap_or_else(|_| path.to_string_lossy().to_string());

    // Match keyword-arg style `kb_collection="foo"` and dict-style `"kb_collection": "foo"`.
    // We deliberately only accept STRING LITERALS — variables are out of scope (would
    // require dataflow analysis and are not the failure mode this doctor is hardening).
    let kw_re = Regex::new(r#"kb_collection\s*=\s*"([^"]+)""#).expect("valid regex");
    let dict_re = Regex::new(r#""kb_collection"\s*:\s*"([^"]+)""#).expect("valid regex");
    let slug_re = Regex::new(r#"slug\s*=\s*"([^"]+)""#).expect("valid regex");

    for (idx, line) in body.lines().enumerate() {
        let captured = kw_re
            .captures(line)
            .or_else(|| dict_re.captures(line))
            .and_then(|c| c.get(1).map(|m| m.as_str().to_string()));
        let Some(kb_value) = captured else {
            continue;
        };
        let agent_slug = nearest_slug_above(&body, idx, &slug_re);
        hits.push(SeedHit {
            rel_path: rel.clone(),
            line: idx + 1,
            agent_slug,
            kb_collection: kb_value,
        });
    }
}

/// Walk a window of up to 40 lines above the hit looking for the nearest `slug="..."`.
fn nearest_slug_above(body: &str, hit_idx: usize, slug_re: &Regex) -> Option<String> {
    let lines: Vec<&str> = body.lines().collect();
    let start = hit_idx.saturating_sub(40);
    for i in (start..hit_idx).rev() {
        if let Some(c) = slug_re.captures(lines[i])
            && let Some(m) = c.get(1)
        {
            return Some(m.as_str().to_string());
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::path::PathBuf;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn temp_repo(label: &str) -> PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0);
        let dir = std::env::temp_dir().join(format!(
            "leio-code-kb-coll-{label}-{}-{nanos}",
            std::process::id()
        ));
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    fn write(root: &Path, rel: &str, body: &str) {
        let path = root.join(rel);
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(path, body).unwrap();
    }

    #[test]
    fn unresolved_kb_collection_is_flagged() {
        let root = temp_repo("unresolved");
        write(
            &root,
            "cartridges/foo/cartridge.toml",
            "name = \"foo\"\ntenant = \"foo_tenant\"\n",
        );
        write(
            &root,
            "cartridges/foo/seed.py",
            "agent = create(\n    slug=\"foo_agent\",\n    kb_collection=\"unknown_kb\",\n)\n",
        );
        let env = doctor_kb_collection_exists(&root);
        assert!(
            env.warnings.iter().any(|w| w.contains("unknown_kb")),
            "{:?}",
            env.warnings
        );
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn tenant_template_match_is_silent() {
        let root = temp_repo("tenant-template");
        write(
            &root,
            "cartridges/bar/cartridge.toml",
            "name = \"bar\"\ntenant = \"bar_tenant\"\n",
        );
        write(
            &root,
            "cartridges/bar/seed.py",
            "create(\n    slug=\"bar_agent\",\n    kb_collection=\"tenant_bar_tenant_knowledge\",\n)\n",
        );
        let env = doctor_kb_collection_exists(&root);
        assert!(
            env.warnings
                .iter()
                .all(|w| !w.contains("tenant_bar_tenant_knowledge")),
            "{:?}",
            env.warnings
        );
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn manifest_match_is_silent() {
        let root = temp_repo("manifest");
        write(
            &root,
            "cartridges/baz/cartridge.toml",
            "name = \"baz\"\ntenant = \"baz_tenant\"\n",
        );
        write(
            &root,
            "cartridges/baz/seed.py",
            "create(\n    slug=\"baz_agent\",\n    kb_collection=\"baz_custom_kb\",\n)\n",
        );
        write(
            &root,
            "deploy/expected_milvus_collections.txt",
            "# manifest\nbaz_custom_kb\n",
        );
        let env = doctor_kb_collection_exists(&root);
        let unresolved: Vec<&String> = env
            .warnings
            .iter()
            .filter(|w| w.contains("baz_custom_kb"))
            .collect();
        assert!(unresolved.is_empty(), "{:?}", env.warnings);
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn missing_manifest_yields_warning() {
        let root = temp_repo("no-manifest");
        write(
            &root,
            "cartridges/qux/cartridge.toml",
            "name = \"qux\"\ntenant = \"qux\"\n",
        );
        write(
            &root,
            "cartridges/qux/seed.py",
            "create(slug=\"qux\", kb_collection=\"tenant_qux_knowledge\")\n",
        );
        let env = doctor_kb_collection_exists(&root);
        assert!(
            env.warnings.iter().any(|w| w.contains(MANIFEST_REL)),
            "{:?}",
            env.warnings
        );
        let _ = fs::remove_dir_all(root);
    }
}
