//! Doctor: `vendored-crate-provenance`
//!
//! Makes copy-vendoring honest.
//!
//! leio-code vendors no crates today: parser functionality (FCA induction)
//! is consumed from pre-built wheels under `artifacts/wheels/` (see
//! `src/fca.rs`). This doctor stays as the guard that keeps any *future*
//! vendored copy honest — `fca-fast-core` once fell a minor release behind
//! upstream while the same lint fixes already existed there, and nothing
//! anywhere reported it.
//!
//! Python solves the equivalent problem for wheels with a checked-in
//! `artifacts/manifest.json` recording name, version and `sha256` per artifact.
//! This doctor is the crate-side analogue: `vendor/manifest.json` records, for
//! every vendored crate, its version, the upstream repo/path/commit it came
//! from, and a content hash of the vendored tree.
//!
//! The property that buys: **a vendored crate cannot be edited, or added,
//! without saying where it now comes from.** Any content change breaks the
//! recorded hash and fails the doctor until the manifest is updated, which
//! forces the editor to state the new upstream commit.
//!
//! ## Policies
//!
//! - `pinned-exact` — the copy is meant to be byte-identical to the named
//!   upstream release.
//! - `pinned-divergent` — the copy deliberately differs from upstream (held
//!   back, or narrowly backported). `note` must say why.
//!
//! The doctor validates the *record*, not the sibling repository: it runs on
//! one `repo_root` and must not depend on another checkout being present.

use std::collections::BTreeSet;
use std::path::Path;
use std::time::Instant;

use serde_json::json;
use sha2::{Digest, Sha256};

use super::Doctor;
use super::utils::query_id;
use crate::model::{EvidenceItem, QueryEnvelope, RepoIndex};

const MANIFEST_REL: &str = "vendor/manifest.json";
const VENDOR_DIR: &str = "vendor";
const VALID_POLICIES: [&str; 2] = ["pinned-exact", "pinned-divergent"];

pub struct VendoredCrateProvenanceDoctor;

impl Doctor for VendoredCrateProvenanceDoctor {
    fn name(&self) -> &'static str {
        "vendored-crate-provenance"
    }

    fn description(&self) -> &'static str {
        "Holds every crate under `vendor/` to a checked-in provenance record in `vendor/manifest.json`: upstream repo/path/commit, declared version matching the vendored Cargo.toml, and a content hash of the vendored tree. Fails when a vendored crate is edited or added without recording where it now comes from — the drift that let two different codebases both claim one version."
    }

    fn run(&self, _index: &RepoIndex, root: &Path) -> QueryEnvelope {
        doctor_vendored_crate_provenance(root)
    }
}

/// Hash a vendored crate directory.
///
/// Every regular file under `dir` except those inside a `target` directory,
/// sorted by forward-slash relative path, fed as `path || 0x00 || bytes || 0x00`.
/// Kept deliberately simple so the value can be regenerated by a short script
/// when a vendored crate is intentionally updated.
pub fn vendored_content_sha256(dir: &Path) -> Option<String> {
    let mut files: Vec<(String, std::path::PathBuf)> = Vec::new();
    let walker = ignore::WalkBuilder::new(dir)
        .hidden(false)
        .git_ignore(false)
        .git_global(false)
        .git_exclude(false)
        .parents(false)
        .build();
    for entry in walker.flatten() {
        if !entry.file_type().is_some_and(|kind| kind.is_file()) {
            continue;
        }
        let abs = entry.path();
        let rel = abs
            .strip_prefix(dir)
            .ok()?
            .to_string_lossy()
            .replace('\\', "/");
        if rel.split('/').any(|part| part == "target") {
            continue;
        }
        files.push((rel, abs.to_path_buf()));
    }
    files.sort_by(|left, right| left.0.as_bytes().cmp(right.0.as_bytes()));

    let mut hasher = Sha256::new();
    for (rel, abs) in files {
        let bytes = std::fs::read(&abs).ok()?;
        hasher.update(rel.as_bytes());
        hasher.update([0u8]);
        hasher.update(&bytes);
        hasher.update([0u8]);
    }
    Some(format!("{:x}", hasher.finalize()))
}

/// Directories directly under `vendor/` that look like a Rust crate.
fn discovered_vendored_crates(root: &Path) -> Vec<String> {
    let mut found = Vec::new();
    let Ok(entries) = std::fs::read_dir(root.join(VENDOR_DIR)) else {
        return found;
    };
    for entry in entries.flatten() {
        if !entry.path().join("Cargo.toml").is_file() {
            continue;
        }
        if let Some(name) = entry.file_name().to_str() {
            found.push(name.to_string());
        }
    }
    found.sort();
    found
}

fn manifest_version(path: &Path) -> Option<String> {
    let text = std::fs::read_to_string(path).ok()?;
    let value = text.parse::<toml::Value>().ok()?;
    value
        .get("package")?
        .get("version")?
        .as_str()
        .map(str::to_string)
}

pub fn doctor_vendored_crate_provenance(root: &Path) -> QueryEnvelope {
    let started = Instant::now();
    let mut warnings: Vec<String> = Vec::new();
    let mut entities: Vec<serde_json::Value> = Vec::new();
    let mut evidence: Vec<EvidenceItem> = Vec::new();

    let discovered = discovered_vendored_crates(root);
    if discovered.is_empty() {
        return QueryEnvelope {
            schema_version: crate::model::SCHEMA_VERSION.to_string(),
            query_id: query_id("doctor_vendored_crate_provenance"),
            kind: "doctor".to_string(),
            summary: "no vendored crates present".to_string(),
            confidence: 0.95,
            entities,
            evidence,
            warnings,
            meta: Some(json!({ "vendored_crates": 0, "manifest": MANIFEST_REL })),
            timing_ms: started.elapsed().as_millis(),
        };
    }

    let manifest_path = root.join(MANIFEST_REL);
    let manifest: Option<serde_json::Value> = std::fs::read_to_string(&manifest_path)
        .ok()
        .and_then(|text| serde_json::from_str(&text).ok());

    let Some(manifest) = manifest else {
        warnings.push(format!(
            "[vendored-crate-provenance] {} vendored crate(s) present but {MANIFEST_REL} is missing or not valid JSON; vendored code has no recorded upstream",
            discovered.len()
        ));
        evidence.push(EvidenceItem {
            kind: "vendor_manifest_missing".to_string(),
            path: MANIFEST_REL.to_string(),
            line: None,
            detail: format!(
                "vendored crates without provenance: {}",
                discovered.join(", ")
            ),
        });
        return QueryEnvelope {
            schema_version: crate::model::SCHEMA_VERSION.to_string(),
            query_id: query_id("doctor_vendored_crate_provenance"),
            kind: "doctor".to_string(),
            summary: format!(
                "{MANIFEST_REL} missing for {} vendored crate(s)",
                discovered.len()
            ),
            confidence: 0.9,
            entities,
            evidence,
            warnings,
            meta: Some(json!({
                "vendored_crates": discovered.len(),
                "recorded_crates": 0,
                "manifest": MANIFEST_REL,
            })),
            timing_ms: started.elapsed().as_millis(),
        };
    };

    let recorded = manifest
        .get("crates")
        .and_then(|value| value.as_array())
        .cloned()
        .unwrap_or_default();
    let mut recorded_names: BTreeSet<String> = BTreeSet::new();
    let mut verified = 0usize;

    for entry in &recorded {
        let name = entry
            .get("name")
            .and_then(|v| v.as_str())
            .unwrap_or("<unnamed>")
            .to_string();
        let rel_path = entry
            .get("path")
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .to_string();
        recorded_names.insert(name.clone());

        let mut issues: Vec<String> = Vec::new();

        let policy = entry.get("policy").and_then(|v| v.as_str()).unwrap_or("");
        if !VALID_POLICIES.contains(&policy) {
            issues.push(format!(
                "policy must be one of {:?}, found `{policy}`",
                VALID_POLICIES
            ));
        }
        for field in ["repo", "path", "commit"] {
            let present = entry
                .get("upstream")
                .and_then(|value| value.get(field))
                .and_then(|value| value.as_str())
                .is_some_and(|value| !value.trim().is_empty());
            if !present {
                issues.push(format!("upstream.{field} is missing"));
            }
        }
        if policy == "pinned-divergent" {
            let has_note = entry
                .get("note")
                .and_then(|v| v.as_str())
                .is_some_and(|value| !value.trim().is_empty());
            if !has_note {
                issues.push("pinned-divergent requires a `note` explaining the divergence".into());
            }
        }

        let crate_dir = root.join(&rel_path);
        if !crate_dir.join("Cargo.toml").is_file() {
            issues.push(format!("`{rel_path}` has no Cargo.toml"));
        } else {
            let declared = entry.get("version").and_then(|v| v.as_str()).unwrap_or("");
            match manifest_version(&crate_dir.join("Cargo.toml")) {
                Some(actual) if actual == declared => {}
                Some(actual) => issues.push(format!(
                    "recorded version `{declared}` but vendored Cargo.toml declares `{actual}`"
                )),
                None => issues.push("vendored Cargo.toml has no [package] version".into()),
            }

            let expected = entry
                .get("content_sha256")
                .and_then(|v| v.as_str())
                .unwrap_or("");
            match vendored_content_sha256(&crate_dir) {
                Some(actual) if actual == expected => verified += 1,
                Some(actual) => issues.push(format!(
                    "content hash mismatch: recorded {expected}, computed {actual} — the vendored copy was changed without updating its provenance"
                )),
                None => issues.push("vendored tree could not be hashed".into()),
            }
        }

        for issue in &issues {
            warnings.push(format!("[vendored-crate-provenance] `{name}`: {issue}"));
            evidence.push(EvidenceItem {
                kind: "vendor_provenance_violation".to_string(),
                path: MANIFEST_REL.to_string(),
                line: None,
                detail: format!("`{name}`: {issue}"),
            });
        }

        entities.push(json!({
            "name": name,
            "path": rel_path,
            "policy": policy,
            "version": entry.get("version").and_then(|v| v.as_str()).unwrap_or(""),
            "upstream": entry.get("upstream").cloned().unwrap_or(json!(null)),
            "verified": issues.is_empty(),
        }));
    }

    // A vendored crate nobody recorded is the exact hole this doctor closes.
    for name in &discovered {
        if recorded_names.contains(name) {
            continue;
        }
        warnings.push(format!(
            "[vendored-crate-provenance] `{name}` is vendored under {VENDOR_DIR}/ but has no entry in {MANIFEST_REL}"
        ));
        evidence.push(EvidenceItem {
            kind: "vendor_crate_unrecorded".to_string(),
            path: format!("{VENDOR_DIR}/{name}"),
            line: None,
            detail: format!("`{name}` has no provenance record"),
        });
    }

    let summary = if warnings.is_empty() {
        format!(
            "{verified} vendored crate(s) match their recorded provenance",
            verified = verified
        )
    } else {
        format!(
            "{} provenance issue(s) across {} vendored crate(s)",
            warnings.len(),
            discovered.len()
        )
    };

    QueryEnvelope {
        schema_version: crate::model::SCHEMA_VERSION.to_string(),
        query_id: query_id("doctor_vendored_crate_provenance"),
        kind: "doctor".to_string(),
        summary,
        confidence: if warnings.is_empty() { 0.95 } else { 0.85 },
        entities,
        evidence,
        warnings,
        meta: Some(json!({
            "vendored_crates": discovered.len(),
            "recorded_crates": recorded.len(),
            "verified_crates": verified,
            "manifest": MANIFEST_REL,
            "contract": "docs/architecture/vendored-crate-provenance.md",
        })),
        timing_ms: started.elapsed().as_millis(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn write(root: &Path, rel: &str, body: &str) {
        let path = root.join(rel);
        std::fs::create_dir_all(path.parent().expect("parent")).expect("mkdir");
        std::fs::write(path, body).expect("write");
    }

    /// Lay down one vendored crate and a manifest whose hash is computed from
    /// the crate as written, so the fixture starts clean.
    fn fixture(policy: &str) -> tempfile::TempDir {
        let temp = tempfile::tempdir().expect("tempdir");
        let root = temp.path();
        write(
            root,
            "vendor/demo/Cargo.toml",
            "[package]\nname = \"demo\"\nversion = \"0.2.0\"\n",
        );
        write(root, "vendor/demo/src/lib.rs", "pub fn demo() {}\n");
        let digest = vendored_content_sha256(&root.join("vendor/demo")).expect("hash");
        write(
            root,
            "vendor/manifest.json",
            &format!(
                r#"{{"schema_version":1,"crates":[{{"name":"demo","version":"0.2.0","path":"vendor/demo","policy":"{policy}","content_sha256":"{digest}","note":"why it differs","upstream":{{"repo":"up","path":"crates/demo","commit":"abc1234"}}}}]}}"#
            ),
        );
        temp
    }

    #[test]
    fn a_recorded_and_unmodified_vendored_crate_is_clean() {
        let temp = fixture("pinned-exact");
        let envelope = doctor_vendored_crate_provenance(temp.path());
        assert!(envelope.warnings.is_empty(), "{:?}", envelope.warnings);
        assert_eq!(envelope.entities.len(), 1);
        assert_eq!(envelope.entities[0]["verified"], true);
    }

    /// The drift that motivated this doctor: vendored source edited in place,
    /// provenance left untouched.
    #[test]
    fn editing_a_vendored_crate_without_updating_provenance_warns() {
        let temp = fixture("pinned-exact");
        write(temp.path(), "vendor/demo/src/lib.rs", "pub fn demo() { }\n");
        let envelope = doctor_vendored_crate_provenance(temp.path());
        assert!(
            envelope
                .warnings
                .iter()
                .any(|warning| warning.contains("content hash mismatch")),
            "{:?}",
            envelope.warnings
        );
    }

    /// The other half: same version number, different code.
    #[test]
    fn a_version_that_disagrees_with_the_vendored_manifest_warns() {
        let temp = fixture("pinned-exact");
        write(
            temp.path(),
            "vendor/demo/Cargo.toml",
            "[package]\nname = \"demo\"\nversion = \"0.1.0\"\n",
        );
        let envelope = doctor_vendored_crate_provenance(temp.path());
        assert!(
            envelope
                .warnings
                .iter()
                .any(|warning| warning.contains("recorded version")),
            "{:?}",
            envelope.warnings
        );
    }

    #[test]
    fn an_unrecorded_vendored_crate_warns() {
        let temp = fixture("pinned-exact");
        write(
            temp.path(),
            "vendor/stowaway/Cargo.toml",
            "[package]\nname = \"stowaway\"\nversion = \"0.1.0\"\n",
        );
        let envelope = doctor_vendored_crate_provenance(temp.path());
        assert!(
            envelope
                .warnings
                .iter()
                .any(|warning| warning.contains("stowaway") && warning.contains("no entry")),
            "{:?}",
            envelope.warnings
        );
    }

    #[test]
    fn a_missing_manifest_warns_rather_than_passing_silently() {
        let temp = fixture("pinned-exact");
        std::fs::remove_file(temp.path().join("vendor/manifest.json")).expect("remove");
        let envelope = doctor_vendored_crate_provenance(temp.path());
        assert!(
            envelope
                .warnings
                .iter()
                .any(|warning| warning.contains("missing or not valid JSON")),
            "{:?}",
            envelope.warnings
        );
    }

    #[test]
    fn a_divergent_pin_without_a_reason_warns() {
        let temp = tempfile::tempdir().expect("tempdir");
        let root = temp.path();
        write(
            root,
            "vendor/demo/Cargo.toml",
            "[package]\nname = \"demo\"\nversion = \"0.2.0\"\n",
        );
        let digest = vendored_content_sha256(&root.join("vendor/demo")).expect("hash");
        write(
            root,
            "vendor/manifest.json",
            &format!(
                r#"{{"schema_version":1,"crates":[{{"name":"demo","version":"0.2.0","path":"vendor/demo","policy":"pinned-divergent","content_sha256":"{digest}","upstream":{{"repo":"up","path":"crates/demo","commit":"abc1234"}}}}]}}"#
            ),
        );
        let envelope = doctor_vendored_crate_provenance(root);
        assert!(
            envelope
                .warnings
                .iter()
                .any(|warning| warning.contains("requires a `note`")),
            "{:?}",
            envelope.warnings
        );
    }

    #[test]
    fn a_missing_upstream_commit_warns() {
        let temp = tempfile::tempdir().expect("tempdir");
        let root = temp.path();
        write(
            root,
            "vendor/demo/Cargo.toml",
            "[package]\nname = \"demo\"\nversion = \"0.2.0\"\n",
        );
        let digest = vendored_content_sha256(&root.join("vendor/demo")).expect("hash");
        write(
            root,
            "vendor/manifest.json",
            &format!(
                r#"{{"schema_version":1,"crates":[{{"name":"demo","version":"0.2.0","path":"vendor/demo","policy":"pinned-exact","content_sha256":"{digest}","upstream":{{"repo":"up","path":"crates/demo"}}}}]}}"#
            ),
        );
        let envelope = doctor_vendored_crate_provenance(root);
        assert!(
            envelope
                .warnings
                .iter()
                .any(|warning| warning.contains("upstream.commit is missing")),
            "{:?}",
            envelope.warnings
        );
    }

    #[test]
    fn a_repo_without_vendored_crates_is_clean() {
        let temp = tempfile::tempdir().expect("tempdir");
        let envelope = doctor_vendored_crate_provenance(temp.path());
        assert!(envelope.warnings.is_empty());
        assert_eq!(envelope.meta.expect("meta")["vendored_crates"], 0);
    }
}
